"""
Polycube representation: pieces as sets of (x, y, z) coordinates,
24 rotations of the cube symmetry group, and placement generation.
"""

import numpy as np
from itertools import product


# 24 rotation matrices for the orientation-preserving symmetries of a cube.
# Generated by composing 90-degree rotations around x, y, z axes.
def _build_rotation_matrices():
    """Build all 24 rotation matrices of the cube symmetry group."""
    # Basic 90-degree rotation matrices
    Rx = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
    Ry = np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]])
    Rz = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
    I = np.eye(3, dtype=int)

    seen = set()
    matrices = []

    # Generate all combinations of rotations
    for ix, iy, iz in product(range(4), repeat=3):
        R = I.copy()
        for _ in range(ix):
            R = R @ Rx
        for _ in range(iy):
            R = R @ Ry
        for _ in range(iz):
            R = R @ Rz
        R = R.astype(int)
        key = tuple(R.flatten())
        if key not in seen:
            seen.add(key)
            matrices.append(R)

    assert len(matrices) == 24, f"Expected 24 rotations, got {len(matrices)}"
    return matrices


ROTATIONS = _build_rotation_matrices()


def normalize(coords):
    """Normalize a piece so its bounding box starts at the origin.

    Args:
        coords: iterable of (x, y, z) tuples

    Returns:
        frozenset of (x, y, z) tuples, translated so min coords are 0
    """
    coords = list(coords)
    if not coords:
        return frozenset()
    min_x = min(c[0] for c in coords)
    min_y = min(c[1] for c in coords)
    min_z = min(c[2] for c in coords)
    return frozenset((x - min_x, y - min_y, z - min_z) for x, y, z in coords)


def rotate(coords, rotation_matrix):
    """Apply a rotation matrix to a set of coordinates.

    Args:
        coords: iterable of (x, y, z) tuples
        rotation_matrix: 3x3 numpy int array

    Returns:
        list of (x, y, z) tuples after rotation
    """
    pts = np.array(list(coords))  # (N, 3)
    rotated = (rotation_matrix @ pts.T).T  # (N, 3)
    return [tuple(row) for row in rotated]


def get_orientations(piece):
    """Get all unique orientations of a piece under the 24 cube rotations.

    Args:
        piece: iterable of (x, y, z) tuples

    Returns:
        list of frozensets, each a unique normalized orientation
    """
    seen = set()
    orientations = []
    for R in ROTATIONS:
        rotated = rotate(piece, R)
        normed = normalize(rotated)
        if normed not in seen:
            seen.add(normed)
            orientations.append(normed)
    return orientations


def get_all_placements(piece, grid_size):
    """Get all valid placements of a piece within an NxNxN grid.

    A placement is a frozenset of (x, y, z) coords, all within [0, grid_size).

    Args:
        piece: iterable of (x, y, z) tuples
        grid_size: int, side length of the target cube

    Returns:
        list of frozensets of (x, y, z) tuples
    """
    orientations = get_orientations(piece)
    placements = []

    for orient in orientations:
        # Bounding box of the normalized orientation
        max_x = max(c[0] for c in orient)
        max_y = max(c[1] for c in orient)
        max_z = max(c[2] for c in orient)

        # Try all translations that keep the piece inside the grid
        for dx in range(grid_size - max_x):
            for dy in range(grid_size - max_y):
                for dz in range(grid_size - max_z):
                    placed = frozenset(
                        (x + dx, y + dy, z + dz) for x, y, z in orient
                    )
                    placements.append(placed)

    return placements


def get_all_placements_rect(piece, gx, gy, gz):
    """Get all valid placements of a piece within a GX x GY x GZ box.

    A placement is a frozenset of (x, y, z) coords, all within
    [0, gx) x [0, gy) x [0, gz).

    Args:
        piece: iterable of (x, y, z) tuples
        gx, gy, gz: dimensions of the target rectangular box

    Returns:
        list of frozensets of (x, y, z) tuples
    """
    orientations = get_orientations(piece)
    placements = []

    for orient in orientations:
        max_x = max(c[0] for c in orient)
        max_y = max(c[1] for c in orient)
        max_z = max(c[2] for c in orient)

        for dx in range(gx - max_x):
            for dy in range(gy - max_y):
                for dz in range(gz - max_z):
                    placed = frozenset(
                        (x + dx, y + dy, z + dz) for x, y, z in orient
                    )
                    placements.append(placed)

    return placements
